### ISSUE TITLE
After updating saved passwords on Keychain is also wiped out.

### ISSUE THREAD

**Issue by Kaizodo** [vantuan88291/react-native-ota-hot-update#63]
when user finishes downloading new update and app restarts using   hotUpdate.resetApp(); all the passwords saved in Keychain  gets erased somehow, and user have to login again.  

am i doing it correctly ?  update is applying applying properly though. just the passwords are beeing cleared whenever i reset the app. 

```tsx
 const [updating, setUpdating] = useState(true);
    const [progress, setProgress] = useState(0);
    const exit = useBackHandler(() => {
        exit();
    });
    const attempt = useRef(0);

    const startUpdate = async () => {
        var downloadUrl = '';
        navigation.setOptions({ headerShown: false });
        var version = route.params.update.version;
        if (Platform.OS === 'android') {
            downloadUrl = route.params.update.downloadAndroidUrl;
        } else if (Platform.OS === 'ios') {
            downloadUrl = route.params.update.downloadIosUrl;
        }

        hotUpdate.downloadBundleUri(ReactNativeBlobUtil, downloadUrl, version, {
            updateSuccess: () => {
                hotUpdate.resetApp();
            },
            updateFail: (message) => {
                setProgress(0);
                if (attempt.current <= 5) {
                    attempt.current = attempt.current + 1;
                    startUpdate();
                } else {
                    Alert.alert('Update failed!', `${message ?? ''}`, [
                        {
                            text: 'Retry',
                            onPress: () => startUpdate(),
                            style: 'cancel',
                        },
                        {
                            text: 'Cancel',
                            onPress: () => hotUpdate.resetApp(),
                            style: 'cancel',
                        },
                    ]);
                }

            },
            restartAfterInstall: true,
            progress(received, total) {
                setProgress(Number(total) > 0 ? Number(received) / Number(total) : 0);
            },
        });
    }
```

**Comment by vantuan88291** [comment]
its weird, as I know rn Keychain is using native method to save the value, I am using expo-secure also and not get this issue, update bundle js not related to the other native side, can you debug more?

**Comment by Kaizodo** [comment]
its actually happening randomly, sometimes it keeps the credentials i am not sure if its plugin issue or my app's issue as i am not changing anything in  keychain during or after the update.  could it be hotUpdate.resetApp() method ?

**Comment by Kaizodo** [comment]
Ok now its confirmed after a update failure if i second attempt is successfuly it removes all keys stores in keychain somehow.  if first attempt is successful then it keeps the key.

**Comment by vantuan88291** [comment]
hotUpdate.resetApp() just restart the app, you can try without it, can just normally quit the app and open again and the latest bundle will apply

**Comment by Kaizodo** [comment]
i checked log cat of app when update fails but i did't get any output all i got was this 

```ts
 ReactNativeJS: undefined <-- i print the error message using updateFail method
ReactNativeJS: 'Download bundle fail', undefined
```

whenever update fails all the credentials in keychain is wipedout  and user have to login again i have beeing trying to solve this issue from very long time now. i think its pluing issue somewere since this code 

```ts
 updateFail: (message) => {
                console.log(message);
{
```
is returning undefined instead of the error what caused the update fail.

**Comment by Kaizodo** [comment]
@vantuan88291  any update on this ? because on samsung devices update is rapidly failing and updateFail method gives undefined as message,  

Also when update fails it wipes out all the credentails in device its kinda weird  issue i am not unable to pin point exactly whats happning because in logs i get undefiend and it happens radnomly  sometimes it works and sometimes it doesn't , also in samsung devices it doesn't work at all.

**Comment by Adam-Planfit** [comment]
Hi, we're also facing a similar issue. When we deploy an update to production users, for some users all values saved in their MMKV storage is wiped out.

**Comment by Kaizodo** [comment]
@vantuan88291  i have checked the bundle zip file it seems ok  as i have extracted both zip file and also checked bundled js file everything looks ok in zip file , also same update works on some devices in one go and on some devices it  fails on first attempt then it succeeds on second attempt but whenever it fails it removes all the saved information in keychain, also on samsung its fail too often. 

Devices i have tested it on :- 

Nothing Phone 1 - Android 15 - Low failure rate 
Samsung A30s - Android 11  - High failure rate 
Honor 8x - Android 10  - Low usually 1 attempt 
Redmi note 5 pro - Android 9  - No failure 


Can you output entire error of download failure instead of undefined so we can pinpoint exactly whats wrong ?

**Comment by Adam-Planfit** [comment]
We've identified that this issue occurs on both iOS and Android. We believe to have found the cause of the issue, but currently we're looking at the iOS side of things.

![Image](https://github.com/user-attachments/assets/913b01b2-1271-433c-9d12-f8816aad1f46)

In the exception handling portion of this library's code there seems to be a step where all the contents of the bundle's parent directory gets deleted if the bundle update fails. We're suspecting that the keychain and MMKV storage contents may reside inside of this parent directory, and gets wiped out in the case of bundle update failure.

This is consistent with @Kaizodo 's findings. 

@vantuan88291 Does this help?

**Comment by vantuan88291** [comment]
thank for your advice, let me check on it

**Comment by vantuan88291** [comment]
![Image](https://github.com/user-attachments/assets/e13dcc29-035e-4f2d-b23a-60f696721ff0)

@Adam-Planfit  seem you are alright, in android call `deleteDirectory(file.parentFile)` it will remove all files inside files folder, that includes mmkv, storage..., I think iOS the same. Tks for the advice and I will fix it soon

**Comment by vantuan88291** [comment]
Fixed at version 2.2.5

**Comment by Adam-Planfit** [comment]
That's great! Thank you

**Comment by Adam-Planfit** [comment]
@vantuan88291 Hi, I opened a PR for the iOS fix. Could you take a look?

**Comment by Adam-Planfit** [comment]
@Kaizodo Hi, I'm trying to simulate an update fail for testing some patches I made. What steps did you take to simulate an update fail?

**Comment by vantuan88291** [comment]
> [@vantuan88291](https://github.com/vantuan88291) Hi, I opened a PR for the iOS fix. Could you take a look?

sure I will check it soon, tks

**Comment by Kaizodo** [comment]
@Adam-Planfit  update was failing randomly i had no clue why update was failing, i also tried disconnecting from internet when  app is still downloading the update.  i have multiple devices and as i mentioend earlier some of the devices were failing update download rapidly  so i got chance to print the error logs which was "undefined".

**Comment by Kaizodo** [comment]
@vantuan88291  yes i rebuilt the app and publish fresh update on google playstore.

**Comment by vantuan88291** [comment]
So weird, just have a line to remove all files folder, can u reproduce it?

**Comment by Kaizodo** [comment]
i am deploying one more update on playstore this time i will deleteing all cache, gradle etc and building it form absolute fresh. then i will be check if it happens again or not. just to be sure if module was not cached.

**Comment by vantuan88291** [comment]
How did you know keychain still missing? Are there any logs?

**Comment by Kaizodo** [comment]
User simply logs out after update failure because keychain data is gone.

**Comment by vantuan88291** [comment]
maybe I will add more log to exception when update failure first

**Comment by vantuan88291** [comment]
@Kaizodo I have deployed 2.2.51 with more exception message, please help to check the root cause why download failed. Thanks

**Comment by Kaizodo** [comment]
Today i cleared all gradle cache, deleted all cache , build, .gradle etc and redeployed fresh copy in playstore and still update is failing for some reason and succeeding on second attempy, and still all keychain data is wipeout. this has gotten worse now as all devices have logged out after update. i am still investigating root cause thanks for adding exception message i will take a look into that.

**Comment by Kaizodo** [comment]
i don't know how do i capture exception form the package but i am still getting undefined when update fails as message 

```ts
hotUpdate.downloadBundleUri(ReactNativeBlobUtil, downloadUrl, version, {
            updateSuccess: () => {
                hotUpdate.resetApp();
            },
            updateFail: (message) => {
                console.log('UPDATE_FAILURE:-', message);
                console.log(message);
                console.log(JSON.stringify(message));
        });
```

```console
04-25 14:13:10.862 14188 14259 I ReactNativeJS: 'UPDATE_FAILURE:-', undefined
04-25 14:13:10.862 14188 14259 I ReactNativeJS: undefined
04-25 14:13:10.862 14188 14259 I ReactNativeJS: undefined
04-25 14:13:10.863 14188 14259 E ReactNativeJS: 'Download bundle fail', undefined
```

**Comment by vantuan88291** [comment]
it weird, no possible to show undefined cuz I just added all in reject case:

![Image](https://github.com/user-attachments/assets/36454f77-daf1-4be3-8f0f-335024f94d5d)

Maybe you can edit at installFail in node module and put some log in there to make sure it latest?

**Comment by Kaizodo** [comment]
in ```installFail ``` you are not passing second argument thats why i am getting undefined 

```'Download bundle fail', undefined```

```ts
  const path = await downloadBundleFile(
      downloadManager,
      uri,
      option?.headers,
      option?.progress
    );
    if (!path) {
      return installFail(option);
    }

    const success = await setupBundlePath(path, option?.extensionBundle);
    if (!success) {
      return installFail(option);
    }
```

**Comment by Kaizodo** [comment]
finally go the error logs , this is the error log 

```json
{"nativeStackAndroid":[],"userInfo":null,"code":"E_UNZIP_FAIL"}
```
it seems its not able to unzip the file however on second attempt its unziping the file successfuly .

**Comment by Kaizodo** [comment]
i did one more test  i though maybe because windows is using compression it might be causing compatibility issue so i removed compression which increased the bundle zip file size from 1.3mb to 5mb and still got same E_UNZIP_FAIL error but on second attempt it ran successfuly but then it removed all keychain data

**Comment by vantuan88291** [comment]
seem you should resolve the zip file first, and one more thing you can try, please set the path file for android like iOS:

![Image](https://github.com/user-attachments/assets/20166f8f-d907-4410-b8aa-fc1f00db7d58)

Just temporary do it first and see whether it's ok. Use downloadManager.fs.dirs.LibraryDir}/${new Date().valueOf()}_hotupdate.zip for android also, I guess Keychain put data in related folder so just change folder to store the bundle first

**Comment by Kaizodo** [comment]
```downloadManager?.fs?.dirs?.LibraryDir``` returns undefined and 
````${downloadManager.fs.dirs.LibraryDir}/${new Date().valueOf()}_hotupdate.zip```` returns ```/1745659460062_hotupdate.zip```

**Comment by Kaizodo** [comment]
here is the stack trace from android unzip function it seems its not detecting the download file , i changed the path from libarary to cache 

```console
04-26 15:29:05.859  6185 13431 I ReactNativeJS: /data/user/0/com.myapp.myapp/cache/1745661545665_hotupdate.zip
04-26 15:29:05.877  6185 13432 W System.err: java.nio.file.NoSuchFileException: /data/user/0/com.myapp.myapp/cache/1745661545665_hotupdate.zip
04-26 15:29:05.881  6185 13432 W System.err:    at sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
04-26 15:29:05.881  6185 13432 W System.err:    at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:150)
04-26 15:29:05.881  6185 13432 W System.err:    at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:115)
04-26 15:29:05.881  6185 13432 W System.err:    at java.nio.file.Files.readAttributes(Files.java:1737)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile$Source.get(ZipFile.java:1375)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:769)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile.<init>(ZipFile.java:283)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile.<init>(ZipFile.java:239)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile.<init>(ZipFile.java:187)
04-26 15:29:05.881  6185 13432 W System.err:    at java.util.zip.ZipFile.<init>(ZipFile.java:201)
04-26 15:29:05.881  6185 13432 W System.err:    at com.otahotupdate.Utils.extractZipFile(Utils.kt:52)
04-26 15:29:05.881  6185 13432 W System.err:    at com.otahotupdate.OtaHotUpdateModule.setupBundlePath(OtaHotUpdateModule.kt:32)
04-26 15:29:05.881  6185 13432 W System.err:    at com.facebook.jni.NativeRunnable.run(Native Method)
04-26 15:29:05.881  6185 13432 W System.err:    at android.os.Handler.handleCallback(Handler.java:959)
04-26 15:29:05.882  6185 13432 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:100)
04-26 15:29:05.882  6185 13432 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
04-26 15:29:05.882  6185 13432 W System.err:    at android.os.Looper.loopOnce(Looper.java:258)
04-26 15:29:05.882  6185 13432 W System.err:    at android.os.Looper.loop(Looper.java:356)
04-26 15:29:05.882  6185 13432 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl.lambda$startNewBackgroundThread$2(MessageQueueThreadImpl.java:217)    
04-26 15:29:05.882  6185 13432 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
04-26 15:29:05.882  6185 13432 W System.err:    at java.lang.Thread.run(Thread.java:1012)
04-26 15:29:05.913  6185 13431 E ReactNativeJS: 'Download bundle fail', '{"nativeStackAndroid":[],"userInfo":null,"code":"E_UNZIP_FAIL"}'

```

**Comment by vantuan88291** [comment]
Can u provide the zip file and let me try with it?

**Comment by Kaizodo** [comment]
i modified 2 functions in native and in javacirpt code and now things seems to work fine , i am not good at native so hopefully you will figure it out whats happening on native part.

1st change - 
in javascipt 
```javascript
const downloadBundleFile = async (downloadManager, uri, headers, callback) => {
  console.log('-------------BEGIN DOWNLOAD----------------------------')
  const path = `${downloadManager.fs.dirs.DocumentDir}/hotupdate/${new Date().valueOf()}_hotupdate.zip`; //<-- here i added DocumentDir/hotupdate folder  because libarary is blank  its most probably due to android versions and new android file system access policies.




  try {
    const res = await downloadManager.config({
      fileCache: _reactNative.Platform.OS === 'android',
      path: path
    }).fetch('GET', uri, {
      ...headers
    }).progress((received, total) => {
      if (callback) {
        callback(received, total);
      }
    });
    console.log(res.path());
    return res.path();
  } catch (error) {
    console.log(error);
    return null;
  }
};
```

and on Native android in ```OtaHotUpdateModule.tk``` file i commented this function 

```//utils.deleteOldBundleIfneeded(null)```  in ```setupBundlePath``` function 

it seems on first attempt the delete function is deleting the zip causing zip module to not detect the file but on second attempt its not deleting the file and on second attempt things are working fine. 

i hope this will give you good insight whats happning and whats going wrong.

**Comment by vantuan88291** [comment]
Can you try keep the path at js side and dont use DocumentDir, i want to know the cause from path folder or deleteOldBundle

**Comment by Kaizodo** [comment]
Yes the root cause seem to be deleteOldBundle code i have restored js code as orignal 2.2.51 and ran update again it went successful

**Comment by vantuan88291** [comment]
thank for that, I will take a look, but first can u help to move deleteOldBundle under extract function to see whether it work? it not a good idea to remove deleteOldBundle, because every time u update the old bundle still there and make your app more heavy

**Comment by Kaizodo** [comment]
Yes i have test it again  root cause is 100% ```utils.deleteOldBundleIfneeded(null)```  when i comment this line everything works fine but when i uncomment it then it fails first attempt then on second attempt it success but wipes all credentials.

**Comment by tuanlevi95** [comment]
<img width="778" alt="Image" src="https://github.com/user-attachments/assets/1f231195-229d-4274-8dfb-f6c22986fe92" />
Can you try to move deleteOldBundleIfneeded under condition like this and see it work?

**Comment by tuanlevi95** [comment]
<img width="624" alt="Image" src="https://github.com/user-attachments/assets/a9d1dab0-7c8a-4d60-8223-6dfd6c11880f" />

@Kaizodo  could you help me to debug this, what is the value of file and path in the first attempt? Cuz i have tried with 3 android devices and not see the issue like you, maybe it related to specific model. Thanks

**Comment by vantuan88291** [comment]
@Kaizodo I have release 2.2.52 to fix that and improve something on android, could u help to try it?

**Comment by Kaizodo** [comment]
@tuanlevi95  i have tested it on variety of devices from android 9 to android 15 , i am not really good at native development so i am not sure if i can give you  proper insight on debug. but i have tested the code in javasript and all values are correct one thing consues me is ```${downloadManager.fs.dirs.LibraryDir}/${new Date().valueOf()}_hotupdate.zip``` line in javascript code as LibraryDir returns blank means it will try to download file in root of device which is not allowed however it still manages to download file in second attempt and manages to extract it as well.

**Comment by vantuan88291** [comment]
@Kaizodo did you try the new version? And how it work?

**Comment by Kaizodo** [comment]
@vantuan88291 

this log is from nothing phone 1 with android 15 

i think somewere something is broken now because react native is not able to detect the bundle here are logs 

```console
04-27 19:31:10.489  7169  7229 E ReactNativeJNI: JSBigFileString::fromPath - Could not open file: /data/user/0/com.myapp.myapp/files/index.android.bundle
04-27 19:31:10.490  7169  7229 W unknown:BridgelessReact: ReactHost{0}.handleHostException(message = "JSBigFileString::fromPath - Could not open file: /data/user/0/com.myapp.myapp/files/index.android.bundle")
```

app is stuck at splash screen which is native when i checked the log i found that it is unable to load the bundle,  i have to publish new update on playstore now. also plugin is suppose to fallback to previous bundle however it seems to be not working as well.

i have tested it on mi note 5 pro (android 9)  with fresh installtion its working but existing users are stuck  at splash screen.

**Comment by vantuan88291** [comment]
@Kaizodo seem it related to main thread on android, I have improved on android that move all unzip, deleting old bundle to IO thread to make sure it not stuck on android but seem some specific android version not suitable with it, just rollback it in version 2.2.53, can try again with it. Thanks

**Comment by Kaizodo** [comment]
@vantuan88291  i haven't tested the latest update 2.2.53 but the previosu update   its breaking on all devices including  mi note 5 pro (android 9). fresh installation goes throguh since it already comes with its bundle, however when i publish new update  and app downloads  it and restarts the app it gets stuck on splash screen (not able to load bundle)

**Comment by Kaizodo** [comment]
@vantuan88291  latest update is also not working , can you check your side if its working for you because for now i will have to switch back to older release till we fix the issue.

**Comment by vantuan88291** [comment]
@Kaizodo latest version is the same as 2.2.51, nothing change without move utils.deleteOldBundleIfneeded under unzip file, and I have tested on android 15, 10, 11 and also work, can u check whether got cache issue?

**Comment by Kaizodo** [comment]
how are deploying the code ? 
for me  my zip file contains following items 

zip file name :- ```index.bundle.android.zip```
contents :- 

- index.android.bundle
- drawable-xhdpi
- drawable-xxhdpi
- ... simmiler other dpi folderrs

when i rename index.android.bundle to index.android.bundle.js i can see the minified javascript starts with following code 

```javascript
var __BUNDLE_START_TIME__=globalThis.nativePerformanceNow?nativePerformanceNow():Date.now(),__DEV__=false,process=globalThis.process||{},__METRO_GLOBAL_PREFIX__='';....other stuff``` 

is this package correct ?

**Comment by Kaizodo** [comment]
also how are we testing the package ? i am testing directly on production (approved by playstore)  maybe its happning on production build only can you confirm.

**Comment by vantuan88291** [comment]
I tested with release mode, same on play store. Or can you try to comment utils.deleteOldBundleIfneeded like you did before and see it working?

**Comment by Kaizodo** [comment]
here is my kotlin code can you check if my implimentation is correct since i am not good at koltin maybe i misconfigured something in native part 

```kotlin
class MainApplication : Application(), ReactApplication {



  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
                add(SplashScreenPackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED

        override fun getJSBundleFile(): String {
             return OtaHotUpdate.bundleJS(this@MainApplication)
        }

      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

  override fun onCreate() {

    super.onCreate()

    SoLoader.init(this, OpenSourceMergedSoMapping)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
  }
}

```


MainActivity

```kotlin
class MainActivity : ReactActivity() {



    override fun onCreate(savedInstanceState: Bundle?) {
        installSplashScreen()
        super.onCreate(savedInstanceState)
        val content: View = findViewById(android.R.id.content)
        content.viewTreeObserver.addOnPreDrawListener(
            object : ViewTreeObserver.OnPreDrawListener {
                override fun onPreDraw(): Boolean {
                    return if (SplashScreenModule.isReady) {
                        content.viewTreeObserver.removeOnPreDrawListener(this)
                        true
                    } else {
                        false
                    }
                }
            }
        )
    }



    /**
   * Returns the name of the main component registered from JavaScript. This is used to schedule
   * rendering of the component.
   */
  override fun getMainComponentName(): String = "Volocals"

  /**
   * Returns the instance of the [ReactActivityDelegate]. We use [DefaultReactActivityDelegate]
   * which allows you to enable New Architecture with a single boolean flags [fabricEnabled]
   */
  override fun createReactActivityDelegate(): ReactActivityDelegate =
      DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)
}

```

i am currneltly using old version 2.2.2 in production which logs out user but still manages to work

**Comment by vantuan88291** [comment]
the config was correct, but can u use 2.2.53 and just temporary comment `utils.deleteOldBundleIfneeded` line to fix the logout issue?

**Comment by Kaizodo** [comment]
i am not sure because app is stuck at splash screen  with new update logout issue seems to be fixed but app gets stuck at splash react native does not find or load bundle file  , i will try with commenting the line, i hope it will work

**Comment by vantuan88291** [comment]
but can you reproduce stuck at splash by your self?

**Comment by Kaizodo** [comment]
App works perfeclty after commenting the deleteOldBundle file code in native

**Comment by vantuan88291** [comment]
> App works perfeclty after commenting the deleteOldBundle file code in native

so if not comment deleteOldBundle, what happened? can try with this? because I have fix something in this function at 2.2.53

**Comment by Kaizodo** [comment]
on 2.2.53 with deleteOldBundle uncommended  app is still getting stuck at splash screen. but this is not happening all the time, its happening randomly currently i am testing on 3 devices sometime sit works on 2 devices and sometime it works on only 1 device.

i have cleared the app's cache and all storage data then i open app it downloads the latest update and it works fine but when i publish same bundle again  it gets stuck at splash screen.

**Comment by vantuan88291** [comment]
Could you give me the log when it got stuck at splash screen?

**Comment by Kaizodo** [comment]
here are the logs
```console

04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderStyle'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderEndColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderTopColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderLeftColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBlockColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderRightColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderStartColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBottomColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderEndEndRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderTopEndRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBlockEndColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderTopLeftRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderEndStartRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderStartEndRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderTopRightRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderTopStartRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBlockStartColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBottomEndRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBottomLeftRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderStartStartRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBottomRightRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.781 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderBottomStartRadius'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.787 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderColor'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.787 11952 12004 W ReactNativeJNI: Component property map contains multiple entries for 'borderStyle'. Ensure all calls to convertRawProp use a consistent prefix, name and suffix.
04-28 18:56:03.803 11952 12004 W unknown:BridgelessReact: ReactHost{0}.getOrCreateReactInstanceTask(): Loading JS Bundle
04-28 18:56:03.804 11952 12004 E ReactNativeJNI: JSBigFileString::fromPath - Could not open file: /data/user/0/com.myapp.myapp/files/index.android.bundle
04-28 18:56:03.806 11952 12004 W unknown:BridgelessReact: ReactHost{0}.handleHostException(message = "JSBigFileString::fromPath - Could not open file: /data/user/0/com.myapp.myapp/files/index.android.bundle")
```

**Comment by vantuan88291** [comment]
so weird, the path of bundle so weird: /data/user/0/com.myapp.myapp/files/index.android.bundle
the unzip function always extract the bundle like this: /data/user/0/com.myapp.myapp/files/output_xxx/index.android.bundle
Can you give me the structure of your bundle file when you zip it? it should be in output folder like this:
```
index.android.bundle.zip
└── output
    ├── index.android.bundle
    └── assets
        ├── icon.png
        ├── logo.jpg
        ├── fonts
        │   ├── xxx.ttf
        │   └── xxx.ttf
        └── images
            ├── xxx
            └── xxx
```

and should not like this:

```
index.android.bundle.zip
    ├── index.android.bundle
    └── assets
        ├── icon.png
        ├── logo.jpg
        ├── fonts
        │   ├── xxx.ttf
        │   └── xxx.ttf
        └── images
            ├── xxx
            └── xxx
```

**Comment by Kaizodo** [comment]
ohh mine is the second one its not in zip/output/index.android.bundle its in zip/index.android.bundle 

its been always like this i did't modify the scripts 

these are my package.json scripts :- 

to publish i simply run ```npm run export-bundlejs```  i am using windows 11 system

```json
{
  "name": "com.myapp.myapp",
  "version": "3.0.0",
  "private": true,
  "scripts": {
    "logs": "adb logcat | grep -i ReactNativeJS",
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start && react-native run-android",
    "build-apk": "cd android && gradlew assembleRelease",
    "build-aab": "cd android && gradlew bundleRelease",
    "test": "jest",
    "export-bundlejs": "npm run export-android && npm run export-ios",
    "export-android": "mkdir dist 2>nul & del dist\\index.bundle.android.zip 2>nul & mkdir android\\output 2>nul & react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\\output\\index.android.bundle --assets-dest android\\output & cd android & powershell -Command \"Compress-Archive -Path output\\* -DestinationPath ../dist/index.bundle.android.zip\" & cd .. & rmdir /s /q android\\output",
    "export-ios": "mkdir dist 2>nul & del dist\\index.bundle.ios.zip 2>nul & mkdir ios\\output 2>nul & react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios\\output\\main.jsbundle --assets-dest ios\\output & cd ios & powershell -Command \"Compress-Archive -Path output\\* -DestinationPath ../dist/index.bundle.ios.zip\" & cd .. & rmdir /s /q ios\\output",
    "export-bytecode": "npm run export-bytecode-android && npm run export-bytecode-ios",
    "export-bytecode-android": "mkdir dist 2>nul & del dist\\hermes.android.hbc.zip 2>nul & mkdir android\\hermes 2>nul & react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\\hermes\\index.android.bundle --assets-dest android\\hermes\\assets && .\\node_modules\\react-native\\sdks\\hermesc\\win64-bin\\hermesc.exe -emit-binary -out android\\hermes\\index.android.hbc android\\hermes\\index.android.bundle -output-source-map -w && del android\\hermes\\index.android.bundle && del android\\hermes\\index.android.hbc.map && powershell -Command \"Compress-Archive -Path android\\hermes\\* -DestinationPath ./dist/hermes.android.hbc.zip\" && rmdir /s /q android\\hermes",
    "export-bytecode-ios": "mkdir dist 2>nul & del dist\\hermes.ios.hbc.zip 2>nul & mkdir ios\\hermes 2>nul & react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios\\hermes\\main.jsbundle --assets-dest ios\\hermes\\assets && .\\node_modules\\react-native\\sdks\\hermesc\\win64-bin\\hermesc.exe -emit-binary -out ios\\hermes\\main.ios.hbc ios\\hermes\\main.jsbundle -output-source-map -w && del ios\\hermes\\main.jsbundle && del ios\\hermes\\main.ios.hbc.map && powershell -Command \"Compress-Archive -Path ios\\hermes\\* -DestinationPath ./dist/hermes.ios.hbc.zip\" && rmdir /s /q ios\\hermes"
  }
}
```

**Comment by Kaizodo** [comment]
i mean i did modify the scripts i am not using orignal script from the documentations  because i was having some issues where zip file was infinitly beeing added into final zip file  generating insanly huge zip file almost freezing the machine.  so i did some modifications. 

zip file structure is like this 

```
index.android.bundle.zip
    ├── index.android.bundle
    └── drawable-mdpi
        ├── node_modules_reactnative_libraries_newappscreen_components_logo.png
        ├── src_assets_logos_dark_lg.png
```

**Comment by vantuan88291** [comment]
U can refer this, it related to window also when export the bundle: https://github.com/vantuan88291/react-native-ota-hot-update/issues/40#issuecomment-2664910829

**Comment by Kaizodo** [comment]
@vantuan88291  can you share your export script ? which you are using to export bundles because i have created new script which seems to be working fine but its missing some android assets (search, back icons on screen header) its probably due to directory misconfuration in command,

**Comment by Lucasdsk** [comment]
@Kaizodo is everything working fine on iOS? I'm experiencing the same issue you described. Once the update is applied the App storage is cleared. I'm trying to debug it to have more info about it to share.

**Comment by Lucasdsk** [comment]
Just got this error on applying the update on an Android 14 running the app on release mode:

Using package version:
`"react-native-ota-hot-update": "^2.2.61",`


```
04-28 19:02:06.165   679   777 E ReactNativeJS: 'Download bundle fail', '{"nativeStackAndroid":[{"lineNumber":59,"file":"OtaHotUpdateModule.kt","methodName":"processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":24,"file":"OtaHotUpdateModule.kt","methodName":"access$processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":72,"file":"OtaHotUpdateModule.kt","methodName":"invokeSuspend","class":"com.otahotupdate.OtaHotUpdateModule$setupBundlePath$1"},{"lineNumber":33,"file":"ContinuationImpl.kt","methodName":"resumeWith","class":"kotlin.coroutines.jvm.internal.BaseContinuationImpl"},{"lineNumber":104,"file":"DispatchedTask.kt","methodName":"run","class":"kotlinx.coroutines.DispatchedTask"},{"lineNumber":111,"file":"LimitedDispatcher.kt","methodName":"run","class":"kotlinx.coroutines.internal.LimitedDispatcher$Worker"},{"lineNumber":99,"file":"Tasks.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.TaskImpl"},{"lineNumber":585,"file":"CoroutineScheduler.kt","methodName":"runSafely","class":"kotlinx.coroutines.scheduling.CoroutineScheduler"},{"lineNumber":802,"file":"CoroutineScheduler.kt","methodName":"executeTask","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":706,"file":"CoroutineScheduler.kt","methodName":"runWorker","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":693,"file":"CoroutineScheduler.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"}],"userInfo":null,"message":"File unzip failed or path is invalid: /data/user/0/myapp.bundleID.app/files/ReactNativeBlobUtilTmp_nx8lqa19jw8j870vtog9p","code":"SET_ERROR"}'
04-28 19:02:06.167   679   679 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
04-28 19:02:06.167   679   679 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
04-28 19:02:06.168   679   778 E unknown:ReactNative: console.error: Download bundle fail {"nativeStackAndroid":[{"lineNumber":59,"file":"OtaHotUpdateModule.kt","methodName":"processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":24,"file":"OtaHotUpdateModule.kt","methodName":"access$processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":72,"file":"OtaHotUpdateModule.kt","methodName":"invokeSuspend","class":"com.otahotupdate.OtaHotUpdateModule$setupBundlePath$1"},{"lineNumber":33,"file":"ContinuationImpl.kt","methodName":"resumeWith","class":"kotlin.coroutines.jvm.internal.BaseContinuationImpl"},{"lineNumber":104,"file":"DispatchedTask.kt","methodName":"run","class":"kotlinx.coroutines.DispatchedTask"},{"lineNumber":111,"file":"LimitedDispatcher.kt","methodName":"run","class":"kotlinx.coroutines.internal.LimitedDispatcher$Worker"},{"lineNumber":99,"file":"Tasks.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.TaskImpl"},{"lineNumber":585,"file":"CoroutineScheduler.kt","methodName":"runSafely","class":"kotlinx.coroutines.scheduling.CoroutineScheduler"},{"lineNumber":802,"file":"CoroutineScheduler.kt","methodName":"executeTask","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":706,"file":"CoroutineScheduler.kt","methodName":"runWorker","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":693,"file":"CoroutineScheduler.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"}],"userInfo":null,"message":"File unzip failed or path is invalid: /data/user/0/myapp.bundleID.app/files/ReactNativeBlobUtilTmp_nx8lqa19jw8j870vtog9p","code":"SET_ERROR"}, js engine: hermes, stack:
```

**Comment by vantuan88291** [comment]
> [@vantuan88291](https://github.com/vantuan88291) can you share your export script ? which you are using to export bundles because i have created new script which seems to be working fine but its missing some android assets (search, back icons on screen header) its probably due to directory misconfuration in command,

here is script for window:


```
"scripts": {
  "export-android": "mkdir android\\output && react-native bundle --platform android --dev false --entry-file index.js --bundle-output android\\output\\index.android.bundle --assets-dest android\\output --sourcemap-output android\\sourcemap.js && cd android && powershell -Command \"Compress-Archive -Path output -DestinationPath index.android.bundle.zip\" && powershell -Command \"Compress-Archive -Path ..\\android\\sourcemap.js -DestinationPath sourcemap.zip\" && cd .. && rmdir /s /q android\\output && del android\\sourcemap.js",
  "export-ios": "mkdir ios\\output && react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios\\output\\main.jsbundle --assets-dest ios\\output --sourcemap-output ios\\sourcemap.js && cd ios && powershell -Command \"Compress-Archive -Path output -DestinationPath main.jsbundle.zip\" && powershell -Command \"Compress-Archive -Path ..\\ios\\sourcemap.js -DestinationPath sourcemap.zip\" && cd .. && rmdir /s /q ios\\output && del ios\\sourcemap.js"
}
```

**Comment by vantuan88291** [comment]
> Just got this error on applying the update on an Android 14 running the app on release mode:
> 
> Using package version:
> 
> ```
> "expo": "~51.0.23",
> "react-native": "0.74.5",
> "react-native-ota-hot-update": "^2.2.61",
> ```
> 
>  ```
> 04-28 19:02:06.165   679   777 E ReactNativeJS: 'Download bundle fail', '{"nativeStackAndroid":[{"lineNumber":59,"file":"OtaHotUpdateModule.kt","methodName":"processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":24,"file":"OtaHotUpdateModule.kt","methodName":"access$processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":72,"file":"OtaHotUpdateModule.kt","methodName":"invokeSuspend","class":"com.otahotupdate.OtaHotUpdateModule$setupBundlePath$1"},{"lineNumber":33,"file":"ContinuationImpl.kt","methodName":"resumeWith","class":"kotlin.coroutines.jvm.internal.BaseContinuationImpl"},{"lineNumber":104,"file":"DispatchedTask.kt","methodName":"run","class":"kotlinx.coroutines.DispatchedTask"},{"lineNumber":111,"file":"LimitedDispatcher.kt","methodName":"run","class":"kotlinx.coroutines.internal.LimitedDispatcher$Worker"},{"lineNumber":99,"file":"Tasks.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.TaskImpl"},{"lineNumber":585,"file":"CoroutineScheduler.kt","methodName":"runSafely","class":"kotlinx.coroutines.scheduling.CoroutineScheduler"},{"lineNumber":802,"file":"CoroutineScheduler.kt","methodName":"executeTask","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":706,"file":"CoroutineScheduler.kt","methodName":"runWorker","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":693,"file":"CoroutineScheduler.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"}],"userInfo":null,"message":"File unzip failed or path is invalid: /data/user/0/myapp.bundleID.app/files/ReactNativeBlobUtilTmp_nx8lqa19jw8j870vtog9p","code":"SET_ERROR"}'
> 04-28 19:02:06.167   679   679 W WindowOnBackDispatcher: OnBackInvokedCallback is not enabled for the application.
> 04-28 19:02:06.167   679   679 W WindowOnBackDispatcher: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
> 04-28 19:02:06.168   679   778 E unknown:ReactNative: console.error: Download bundle fail {"nativeStackAndroid":[{"lineNumber":59,"file":"OtaHotUpdateModule.kt","methodName":"processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":24,"file":"OtaHotUpdateModule.kt","methodName":"access$processBundleFile","class":"com.otahotupdate.OtaHotUpdateModule"},{"lineNumber":72,"file":"OtaHotUpdateModule.kt","methodName":"invokeSuspend","class":"com.otahotupdate.OtaHotUpdateModule$setupBundlePath$1"},{"lineNumber":33,"file":"ContinuationImpl.kt","methodName":"resumeWith","class":"kotlin.coroutines.jvm.internal.BaseContinuationImpl"},{"lineNumber":104,"file":"DispatchedTask.kt","methodName":"run","class":"kotlinx.coroutines.DispatchedTask"},{"lineNumber":111,"file":"LimitedDispatcher.kt","methodName":"run","class":"kotlinx.coroutines.internal.LimitedDispatcher$Worker"},{"lineNumber":99,"file":"Tasks.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.TaskImpl"},{"lineNumber":585,"file":"CoroutineScheduler.kt","methodName":"runSafely","class":"kotlinx.coroutines.scheduling.CoroutineScheduler"},{"lineNumber":802,"file":"CoroutineScheduler.kt","methodName":"executeTask","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":706,"file":"CoroutineScheduler.kt","methodName":"runWorker","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"},{"lineNumber":693,"file":"CoroutineScheduler.kt","methodName":"run","class":"kotlinx.coroutines.scheduling.CoroutineScheduler$Worker"}],"userInfo":null,"message":"File unzip failed or path is invalid: /data/user/0/myapp.bundleID.app/files/ReactNativeBlobUtilTmp_nx8lqa19jw8j870vtog9p","code":"SET_ERROR"}, js engine: hermes, stack:
> ```

this issue seem the zip file you have downloaded invalid, please verify it after downloaded

**Comment by Kaizodo** [comment]
@vantuan88291  thanks for the scripts , i ran some tests and it seems to be working fine now.  it was a zip file folder structure after all. man this simple thing caused  soo much trouble.

Also when i published the hbc bundle instead of js bundle app  was keep restarting and updataing again and again, it did it for like 2-3 times then it finally got updated.  i think with hbc its saving the current bundle version or something, i have yet to run some more tests on hbc bundles. if i face the issue again i will let you know.  for now js bundles are working perfectly fine.

**Comment by vantuan88291** [comment]
> [@vantuan88291](https://github.com/vantuan88291) thanks for the scripts , i ran some tests and it seems to be working fine now. it was a zip file folder structure after all. man this simple thing caused soo much trouble.
> 
> Also when i published the hbc bundle instead of js bundle app was keep restarting and updataing again and again, it did it for like 2-3 times then it finally got updated. i think with hbc its saving the current bundle version or something, i have yet to run some more tests on hbc bundles. if i face the issue again i will let you know. for now js bundles are working perfectly fine.

for hbc, the flow of OTA no different, I have tried with my project from js to .hbc and nothing change without the app startup faster

**Comment by Kaizodo** [comment]
That was probably some cache issue i ran some tests and seems to be working perfectly fine with both js and hbc bundle. thanks for propt responses and help in fixing the bug. 

Following issues are confirmed fixed on android :- 

Package Version :- 2.2.53 

1. After updating saved passwords on Keychain is also wiped out
2. App stuck at splash screen - due to incorrect zip file directory structure 
3. hbc bundle and js bundle both are working perfectly fine 

Make sure zip file directory structure is like following (all content should be inside output folder):- 
```text
index.android.bundle.zip
└── output
    ├── index.android.bundle
    └── assets
        ├── icon.png
        ├── logo.jpg
        ├── fonts
        │   ├── xxx.ttf
        │   └── xxx.ttf
        └── images
            ├── xxx
            └── xxx

```

We can mark it as completed however i haven't tested on IOS.

**Comment by vantuan88291** [comment]
Please help to try version 2.2.61, tks @Kaizodo

**Comment by planfit** [comment]
@vantuan88291
Hello, I'm trying to build the Android with version 2.2.61, but a build error is occurring. Could you please take a look?

> Task :react-native-ota-hot-update:compileReleaseKotlin FAILED  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:13:8 Unresolved reference: kotlinx  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:14:8 Unresolved reference: kotlinx  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:15:8 Unresolved reference: kotlinx  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:16:8 Unresolved reference: kotlinx  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:23:5 Unresolved reference: GlobalScope  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:23:24 Unresolved reference: Dispatchers  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:24:7 Unresolved reference: delay  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:45:7 Unresolved reference: GlobalScope  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:45:26 Unresolved reference: Dispatchers  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:46:9 Unresolved reference: delay  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdate.kt:6:27 Unresolved reference: BaseReactPackage  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdate.kt:18:22 Unresolved reference: BaseReactPackage  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdate.kt:19:3 'getModule' overrides nothing  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdate.kt:27:3 'getReactModuleInfoProvider' overrides nothing  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdate.kt:37:9 No value passed for parameter 'p6'  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdateModule.kt:16–21 Unresolved reference: kotlinx  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdateModule.kt:27 Unresolved reference: CoroutineScope, SupervisorJob, Dispatchers  
e: .../node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/OtaHotUpdateModule.kt:73, 77 Unresolved reference: withContext, Dispatchers  


Let me know if you need additional context or logs. Thanks in advance!

**Comment by tuanlevi95** [comment]
this one happened when u build the app or run app and got crash? @planfit

**Comment by Kaizodo** [comment]
@vantuan88291  my build was successful i haven't tested it yet i have to publish it on playstore first but i got this warning though 

```console
node_modules/react-native-ota-hot-update/android/src/main/java/com/otahotupdate/CrashHandler.kt:45:7 
This is a delicate API and its use requires care. Make sure you fully read and understand documentation
 of the declaration that is marked as a delicate API.
```

**Comment by planfit** [comment]
@vantuan88291 
There was no problem in version 2.1.0, but
if I want to fix the issue where the parent directory gets deleted when CodePush fails on iOS and Android after applying a manual patch in 2.1.0, how should I do it?

react native version : 0.71.13

**Comment by planfit** [comment]
@vantuan88291 

[Summary]
I faced build issues when trying to integrate react-native-ota-hot-update into a React Native 0.71.12 project.
Mainly, the problems were caused by the usage of BaseReactPackage, which is deprecated in newer versions of React Native, and missing kotlinx-coroutines dependencies.

Here’s the step-by-step solution I applied.

[Problem]
BaseReactPackage is not available in React Native 0.71+.

Kotlin unresolved references to kotlinx.coroutines.

getVersionCode() function missing due to class structure changes.

OtaHotUpdate class and related setup were broken.

[Solution]
1. Add missing kotlinx-coroutines dependencies
In node_modules/react-native-ota-hot-update/android/build.gradle, add:

```
dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
}

```
2. Refactor OtaHotUpdate.kt
Changed the OtaHotUpdate class to implement ReactPackage directly instead of extending BaseReactPackage.

Kept the class name OtaHotUpdate to minimize breaking changes.

Inside OtaHotUpdate.kt, redefined createNativeModules() and createViewManagers().

```

class OtaHotUpdate : ReactPackage {
    override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
        return listOf(OtaHotUpdateModule(reactContext))
    }

    override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
        return emptyList()
    }

    companion object {
        // getVersionCode() and bundleJS() methods are kept inside the companion object.
    }
}
```

3. Update MainApplication.java
Imported OtaHotUpdate.

In getPackages(), manually added new OtaHotUpdate().

In getJSBundleFile(), called OtaHotUpdate.Companion.bundleJS(getApplicationContext()).
```

import com.otahotupdate.OtaHotUpdate;

@Override
protected List<ReactPackage> getPackages() {
  List<ReactPackage> packages = new PackageList(this).getPackages();
  packages.add(new OtaHotUpdate()); // Added manually
  return packages;
}

@Override
protected String getJSBundleFile() {
  return OtaHotUpdate.Companion.bundleJS(getApplicationContext());
}

```

You could also consider updating the library to fully support TurboModules and New Architecture in future versions, but with the above changes, it works properly in RN 0.71+ projects for now.

**Comment by vantuan88291** [comment]
> [@vantuan88291](https://github.com/vantuan88291)
> 
> [Summary] I faced build issues when trying to integrate react-native-ota-hot-update into a React Native 0.71.12 project. Mainly, the problems were caused by the usage of BaseReactPackage, which is deprecated in newer versions of React Native, and missing kotlinx-coroutines dependencies.
> 
> Here’s the step-by-step solution I applied.
> 
> [Problem] BaseReactPackage is not available in React Native 0.71+.
> 
> Kotlin unresolved references to kotlinx.coroutines.
> 
> getVersionCode() function missing due to class structure changes.
> 
> OtaHotUpdate class and related setup were broken.
> 
> [Solution]
> 
> 1. Add missing kotlinx-coroutines dependencies
>    In node_modules/react-native-ota-hot-update/android/build.gradle, add:
> 
> ```
> dependencies {
>     implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
>     implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
> }
> ```
> 
> 2. Refactor OtaHotUpdate.kt
>    Changed the OtaHotUpdate class to implement ReactPackage directly instead of extending BaseReactPackage.
> 
> Kept the class name OtaHotUpdate to minimize breaking changes.
> 
> Inside OtaHotUpdate.kt, redefined createNativeModules() and createViewManagers().
> 
> ```
> 
> class OtaHotUpdate : ReactPackage {
>     override fun createNativeModules(reactContext: ReactApplicationContext): List<NativeModule> {
>         return listOf(OtaHotUpdateModule(reactContext))
>     }
> 
>     override fun createViewManagers(reactContext: ReactApplicationContext): List<ViewManager<*, *>> {
>         return emptyList()
>     }
> 
>     companion object {
>         // getVersionCode() and bundleJS() methods are kept inside the companion object.
>     }
> }
> ```
> 
>  3. Update MainApplication.java
>    Imported OtaHotUpdate.
> 
> In getPackages(), manually added new OtaHotUpdate().
> 
> In getJSBundleFile(), called OtaHotUpdate.Companion.bundleJS(getApplicationContext()).
> 
> ```
> 
> import com.otahotupdate.OtaHotUpdate;
> 
> @Override
> protected List<ReactPackage> getPackages() {
>   List<ReactPackage> packages = new PackageList(this).getPackages();
>   packages.add(new OtaHotUpdate()); // Added manually
>   return packages;
> }
> 
> @Override
> protected String getJSBundleFile() {
>   return OtaHotUpdate.Companion.bundleJS(getApplicationContext());
> }
> ```
> 
> You could also consider updating the library to fully support TurboModules and New Architecture in future versions, but with the above changes, it works properly in RN 0.71+ projects for now.

Let me see on this, thank for your information
